[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
  tzapu/WiFiManager
  bblanchon/ArduinoJson
  bodmer/TFT_eSPI
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git

; Use the CYD display configuration checked into this repository.
build_flags =
  -I .
  -DUSER_SETUP_LOADED=1
  -include User_Setup.h
